version: '3.7'
services:
  kv_server:
    build: .
    
    ports:
      - "5000:5000"
    environment:
      - "KV_SERVER_PORT=5000"
      - "KV_SERVER_REPLICAS=1"
      - "KV_SERVER_REPLICA_ID=0"
      - "KV_SERVER_REPLICA_HOSTS=kv_server"
  stress:
    build: ./tests/stress
    environment:
      - "KV_SERVER_HOST=kv_server"
      - "KV_SERVER_PORT=5000"
    command: /run/tests.sh
    depends_on:
      - kv_server
