// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package proto_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UniversalResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UniversalResponse) Reset()         { *m = UniversalResponse{} }
func (m *UniversalResponse) String() string { return proto.CompactTextString(m) }
func (*UniversalResponse) ProtoMessage()    {}
func (*UniversalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *UniversalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UniversalResponse.Unmarshal(m, b)
}
func (m *UniversalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UniversalResponse.Marshal(b, m, deterministic)
}
func (m *UniversalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniversalResponse.Merge(m, src)
}
func (m *UniversalResponse) XXX_Size() int {
	return xxx_messageInfo_UniversalResponse.Size(m)
}
func (m *UniversalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UniversalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UniversalResponse proto.InternalMessageInfo

func (m *UniversalResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UniversalResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*UniversalResponse)(nil), "proto_api.UniversalResponse")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x53, 0xf1, 0x89, 0x05, 0x99,
	0x4a, 0xce, 0x5c, 0x82, 0xa1, 0x79, 0x99, 0x65, 0xa9, 0x45, 0xc5, 0x89, 0x39, 0x41, 0xa9, 0xc5,
	0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x12, 0x5c, 0xec, 0xc5, 0xa5, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x30, 0xae, 0x90, 0x08, 0x17, 0x6b, 0x6a, 0x51, 0x51,
	0x7e, 0x91, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0xe3, 0xc4, 0x1b, 0xc5, 0xad, 0xa7,
	0x0f, 0x37, 0x33, 0x89, 0x0d, 0xcc, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xad, 0xad, 0x61,
	0x19, 0x75, 0x00, 0x00, 0x00,
}
