// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_service.proto

package proto_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2f965b42940ea8, []int{0}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

type GetStatusResponse struct {
	CommonResponse       *UniversalResponse `protobuf:"bytes,1,opt,name=common_response,json=commonResponse,proto3" json:"common_response,omitempty"`
	Status               *ServerStatus      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2f965b42940ea8, []int{1}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetCommonResponse() *UniversalResponse {
	if m != nil {
		return m.CommonResponse
	}
	return nil
}

func (m *GetStatusResponse) GetStatus() *ServerStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ServerStatus struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStatus) Reset()         { *m = ServerStatus{} }
func (m *ServerStatus) String() string { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()    {}
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2f965b42940ea8, []int{2}
}

func (m *ServerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatus.Unmarshal(m, b)
}
func (m *ServerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatus.Marshal(b, m, deterministic)
}
func (m *ServerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatus.Merge(m, src)
}
func (m *ServerStatus) XXX_Size() int {
	return xxx_messageInfo_ServerStatus.Size(m)
}
func (m *ServerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatus proto.InternalMessageInfo

func (m *ServerStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServerStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type StartRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2f965b42940ea8, []int{3}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

type StartResponse struct {
	CommonResponse       *UniversalResponse `protobuf:"bytes,1,opt,name=common_response,json=commonResponse,proto3" json:"common_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2f965b42940ea8, []int{4}
}

func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (m *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(m, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

func (m *StartResponse) GetCommonResponse() *UniversalResponse {
	if m != nil {
		return m.CommonResponse
	}
	return nil
}

type StopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2f965b42940ea8, []int{5}
}

func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (m *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(m, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

type StopResponse struct {
	CommonResponse       *UniversalResponse `protobuf:"bytes,1,opt,name=common_response,json=commonResponse,proto3" json:"common_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2f965b42940ea8, []int{6}
}

func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (m *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(m, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

func (m *StopResponse) GetCommonResponse() *UniversalResponse {
	if m != nil {
		return m.CommonResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*GetStatusRequest)(nil), "proto_api.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "proto_api.GetStatusResponse")
	proto.RegisterType((*ServerStatus)(nil), "proto_api.ServerStatus")
	proto.RegisterType((*StartRequest)(nil), "proto_api.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "proto_api.StartResponse")
	proto.RegisterType((*StopRequest)(nil), "proto_api.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "proto_api.StopResponse")
}

func init() { proto.RegisterFile("server_service.proto", fileDescriptor_8c2f965b42940ea8) }

var fileDescriptor_8c2f965b42940ea8 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x25, 0x08, 0x8a, 0x72, 0x49, 0x0a, 0x9c, 0x50, 0x1b, 0x85, 0x0e, 0x28, 0x13, 0x53, 0x2a,
	0x95, 0x09, 0x89, 0x01, 0x21, 0x21, 0x98, 0x13, 0x95, 0x81, 0x25, 0x0a, 0x95, 0x87, 0x48, 0x34,
	0x0e, 0xb6, 0xdb, 0x3f, 0xc1, 0xbf, 0xe3, 0x17, 0x21, 0x7f, 0xca, 0xa1, 0x8c, 0x99, 0xec, 0xbb,
	0xf3, 0x7b, 0xcf, 0xf7, 0x1e, 0x5c, 0x71, 0xc2, 0xf6, 0x84, 0xd5, 0xf2, 0x68, 0x37, 0xa4, 0xe8,
	0x19, 0x15, 0x14, 0x43, 0x75, 0xd4, 0x4d, 0xdf, 0x66, 0xf1, 0x86, 0x6e, 0xb7, 0xb4, 0xd3, 0x83,
	0x1c, 0xe1, 0xe2, 0x85, 0x88, 0x4a, 0x34, 0x62, 0xc7, 0x4b, 0xf2, 0xb5, 0x23, 0x5c, 0xe4, 0xdf,
	0x01, 0x5c, 0x7a, 0x4d, 0xde, 0xd3, 0x8e, 0x13, 0x7c, 0x86, 0x73, 0x8d, 0xac, 0x99, 0x69, 0xa5,
	0xc1, 0x4d, 0x70, 0x1b, 0xad, 0x16, 0x85, 0x23, 0x2f, 0xd6, 0x5d, 0xbb, 0x27, 0x8c, 0x37, 0x9f,
	0x16, 0x56, 0x4e, 0x35, 0xc8, 0xd1, 0x2c, 0x61, 0xc2, 0x15, 0x71, 0x7a, 0xac, 0xd0, 0x73, 0x0f,
	0x5d, 0xa9, 0xaf, 0x1b, 0x5d, 0xf3, 0x2c, 0x7f, 0x84, 0xd8, 0xef, 0x63, 0x0a, 0x67, 0x52, 0xa2,
	0xa5, 0x9d, 0xd2, 0x0f, 0x4b, 0x5b, 0xe2, 0x6c, 0x40, 0x1d, 0x3a, 0x86, 0x29, 0xc4, 0x95, 0x68,
	0x98, 0xb0, 0xfb, 0xbd, 0x41, 0x62, 0xea, 0x51, 0x57, 0xcb, 0x13, 0x88, 0x2a, 0x41, 0x7b, 0x2b,
	0xb3, 0x96, 0xb2, 0xb2, 0x1c, 0x55, 0x65, 0xf5, 0x13, 0x40, 0x62, 0x0c, 0xd1, 0x11, 0xe3, 0x2b,
	0x84, 0x2e, 0x2e, 0xbc, 0xf6, 0xc8, 0xfe, 0x26, 0x9b, 0x2d, 0xfe, 0x1f, 0x9a, 0xff, 0x1f, 0xe1,
	0x03, 0x9c, 0x2a, 0x67, 0x70, 0x90, 0x8a, 0xe7, 0x5d, 0x96, 0x1e, 0x0e, 0x1c, 0xfa, 0x1e, 0x4e,
	0xe4, 0xc2, 0x38, 0x1b, 0xbc, 0x71, 0x86, 0x64, 0xf3, 0x83, 0xbe, 0x85, 0x3e, 0x25, 0xef, 0x51,
	0xb1, 0x74, 0xd3, 0x8f, 0x89, 0xba, 0xde, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xd1, 0x3e,
	0x38, 0xcd, 0x02, 0x00, 0x00,
}
